### ISSUE TITLE
CAMP does not detect mismatches between values and realization

### ISSUE THREAD

**Issue by fchauvel** [STAMP-project/camp#39]
#### Characteristics

-   **Issue Type**: \[bug]
-   **Reproducibility**: always
-   **Severity**: minor
-   **Tool/Service/Component**: camp v0.3.3
-   **Execution Environment**: Debian 9
-   **Reporter**: @fchauvel

#### Description
CAMP does not detect when there is a mismatch between the number of value provided for a given variable, and the number of value provided in the realization. For instance, in the following snippet, I declare two values but I give 3 substitutions. 

```yaml
     flask:
        values: [ v0.12.4, v1.0.1 ]
        realization:
         - targets: [ greetings/setup.py ]
           pattern: "flask == 1.0.2"
           replacements:
             - flask == 0.12.4
             - flask == 1.0.1
             - flask == 1.0.2
```

### Steps to reproduce
Simply run the `camp generate`command. No warning or error is reported.

#### Relationships
Relate to Issue #21 about model model validation.
