### ISSUE TITLE
CAMP does not warn about substitutions for which no match is found

### ISSUE THREAD

**Issue by fchauvel** [STAMP-project/camp#40]
#### Characteristics

-   **Issue Type**: bug
-   **Reproducibility**: always
-   **Severity**: minor
-   **Tool/Service/Component**: CAMP 0.3.3
-   **Execution Environment**: Debian 9
-   **Reporter**: @fchauvel 

#### Description
CAMP does not warn about substitition for which no match is performed. CAMP silently generate consistently generate configuration without realizing the variable.

#### Steps to reproduce
Create a CAMP modle where one component declares a variable, whose realization is broken. For instance, in the example below, the issue occurs when the DockerFile does not contain the selected pattern `python:3.7-slim-stretch`.

```yaml
    variables:                                                                                                                                                                                                     
      python:                                                                                                                                                                                                      
        values: [ v2.7, v3.5, v3.7 ]                                                                                                                                                                               
        realization:                                                                                                                                                                                               
         - targets: [ greetings/Dockerfile ]                                                                                                                                                                       
           pattern: "python:3.7-slim-stretch"                                                                                                                                                                      
           replacements:                                                                                                                                                                                           
             - python:2.7-slim-stretch                                                                                                                                                                             
             - python:3.5-slim-stretch                                                                                                                                                                             
             - python:3.7-slim-stretch

```
