### ISSUE TITLE
CAMP realize fails when target file is deep into the template directory structure

### ISSUE THREAD

**Issue by fchauvel** [STAMP-project/camp#48]
#### Characteristics

-   **Issue Type**: bug
-   **Reproducibility**: always
-   **Severity**: major
-   **Tool/Service/Component**: CAMP v0.3.5
-   **Execution Environment**: Debian 9 / Python 3.5
-   **Reporter**: Franck Chauvel

#### Description

CAMP realize fails to perform substitutions when they target a file within a nested structure directory in the template. such as `sphinx/src/setup.py`.

#### Steps to reproduce

For instance, in the following snippet I declare a variable whose realization targets the file `sphinx/src/setup.py`.

```yaml
variables:
      jinja2:
        values: [ v2.3, v2.3.1 ]
        realization:
         - targets: [ sphinx/src/setup.py ]
           pattern: 'Jinja2>=2.3'
           replacements:
             - Jinja2==2.3
             - Jinja2==2.3.1
```
When I run CAMP generate, I got the following error:

```console
$ camp realize -d .
CAMP v0.3.5 (MIT)
Copyright (C) 2017 -- 2019 SINTEF Digital

Loaded './camp.yml'.
Loading configurations from './out' ...
Unexpected error:
 - [Errno 2] No such file or directory: './out/config_1/images/sphinx_0/setup.py'
   In file: /home/fchauvel/Documents/camp/camp/realize.py
      169: with open(path, "r") as resource_file:
   Please report this at 'https://github.com/STAMP-project/camp/issues'.

That's all folks!
```

Which indicates that CAMP search a file a the `sphinx` directory of the template, instead of searching it in the `src` directory.

#### Other files and URLs

Here is the structure of my CAMP project
```console
 tree .
.
├── camp.yml
├── out
│   ├── config_1
│   │   ├── configuration.dot
│   │   ├── configuration.yml
│   │   └── images
│   │       └── sphinx_0
│   │           ├── Dockerfile
│   │           └── src
│   │               └── setup.py
│   └── config_2
│       ├── configuration.dot
│       └── configuration.yml
├── template
│   └── sphinx
│       ├── Dockerfile
│       └── src
│           └── setup.py
└── z3_errors.log

9 directories, 10 files
```
#### Relationships
None
