### ISSUE TITLE
how to invoke deployment of the configurations generated by camp

### ISSUE THREAD

**Issue by vassik** [STAMP-project/camp#6]
Please refer to https://github.com/STAMP-project/camp-samples/issues/1 for the initial discussions

wrote by @fermenreq
```
Hi Anatoly, 

Thanks! It works ! 

The above sources and directories has been generated and my question is how to deploy CityGo with the new configurations ?  

root@osboxes:/home/osboxes/Proyectos/STAMP/WP2_ATOS_USE_CASE/CAMP/camp-samples/atos# ls
ampcompose.yml  build     compose2       docker-compose  genimages.yml  out   resolmodel.yml  variables.yml~
ampimages.yml   compose1  composite.yml  features.yml    images.yml     repo  variables.yml

It could be better if we have some steps in the Readme 

Bests,
Fernando
```

**Comment by vassik** [comment]
Hi @fermenreq. This is great.

You get two compose files, the first one is in 'atos/compose1' and another on is located in 'atos/compose2'. Thus in order to deploy them you just need to run the 'docker-compose up' command. 

However, each of the compose files relies on two images which are located in the 'atos/build' directory, i.e. one for the db and another one for the showcase application. These images are taken from the db and webapp folders of https://gitlab.ow2.org/stamp/atos-uc-city2go/tree/master/Descriptors/Docker. You can build them by running build.sh in the 'atos/build' directory

**Comment by fermenreq** [comment]
Hi @vassik , thanks for your quick reply. 

I have an error during the deployment using your comment before. It's pulling an extrange image

```
Pulling db (postgres:none-ubuntu-latest)...
```

```
root@osboxes:/home/osboxes/Proyectos/STAMP/WP2_ATOS_USE_CASE/CAMP/camp-samples/atos/compose2# docker-compose up -d
Creating network "compose2_default" with the default driver
Pulling mongo (mongo:3.2)...
3.2: Pulling from library/mongo
4d0d76e05f3c: Pull complete
2da2ecd7fdbd: Pull complete
c3a86da34d0f: Pull complete
e2b1f447e420: Pull complete
c9e820834b36: Pull complete
95cc146d3e5b: Pull complete
ca178240d8e8: Pull complete
08eb6ad571c5: Pull complete
7c119b19e0f1: Pull complete
1f4aacdd6e75: Pull complete
0bd5a923b552: Pull complete
Digest: sha256:79a6176ef96dd22a8b5739fbacc310cfd65c75566a6f08e58069bab28289f368
Status: Downloaded newer image for mongo:3.2
Pulling db (postgres:none-ubuntu-latest)...
ERROR: manifest for postgres:none-ubuntu-latest not found
root@osboxes:/home/osboxes/Proyectos/STAMP/WP2_ATOS_USE_CASE/CAMP/camp-samples/atos/compose2# ls
docker-compose.yml
```

## Docker-compose file  ( compose 2 )

```
services:
  cygnus-common:
    container_name: cygnus-common
    environment:
    - CYGNUS_LOG_LEVEL=DEBUG
    - CYGNUS_SERVICE_PORT=5050
    - CYGNUS_API_PORT=8081
    - CYGNUS_MYSQL_PORT=3306
    - MVN_VER=3.5.2
    - FLUME_VER=1.4.0
    - JAVA_VERSION=1.8.0
    - CYGNUS_USER=cygnus
    expose:
    - '8081'
    image: fiware/cygnus-common
  cygnus-ngsi:
    container_name: cygnus-ngsi
    environment:
    - CYGNUS_CARTO_USER=
    - CYGNUS_CARTO_KEY=
    - CYGNUS_LOG_LEVEL=DEBUG
    - CYGNUS_SERVICE_PORT=5050
    - CYGNUS_API_PORT=8081
    - CYGNUS_MYSQL_PORT=3306
    - MVN_VER=3.5.2
    - FLUME_VER=1.4.0
    - JAVA_VERSION=1.8.0
    - CYGNUS_USER=cygnus
    expose:
    - '8081'
    image: fiware/cygnus-ngsi
  db:
    container_name: my_postgres
    environment:
    - max_connections=500
    - shared_buffers=256
    - port=5432
    - POSTGRES_DB=
    - POSTGRES_USER=
    - POSTGRES_PASSWORD=
    - PGDATA=/var/lib/postgresql/data/pgdata
    expose:
    - '5432'
    image: postgres:none-ubuntu-latest
    ports:
    - 5432:5432
  mongo:
    command: --nojournal
    expose:
    - '27017'
    image: mongo:3.2
    ports:
    - 27017:27017
  orion:
    command: -dbhost mongo
    depends_on:
    - mongo
    expose:
    - '1026'
    image: fiware/orion
    links:
    - mongo
    ports:
    - 1026:1026
  web:
    command: python /webapp/ShowcaseServer/manage.py runserver 0.0.0.0:80
    container_name: my_web
    depends_on:
    - db
    - orion
    environment:
    - PYTHONUSERBASE=.webapp/ShowcaseServer/
    - StartServers=2
    - MinSpareThreads=25
    - MaxSpareThreads=75
    - ThreadLimit=64
    - ThreadsPerChild=0
    - MaxRequestWorkers=150
    - MaxConnectionsPerChild=0
    - MinSpareServers=5
    - MaxSpareServers=10
    image: showcase:none-python-2.7
    ports:
    - 80:80
    volumes:
    - ./webapp:/webapp
version: '2'
volumes:
  db_data:
    external: true
```
It's mandatory to build this images before deploy ? If yes, in ```root@osboxes:/home/osboxes/Proyectos/STAMP/WP2_ATOS_USE_CASE/CAMP/camp-samples/atos/build/showcase--python-2.7# ls
mpm_prefork-template.conf  mpm_worker-template.conf  ShowcaseServer ``` there are no ```build.sh``` file


Thanks,
Fernando Méndez - fernando.mendez@atos.net

**Comment by vassik** [comment]
@fermenreq Yes, you need to build these images beforehand. In the compose files there is a reference to these images.

Note:
You actually build these images in your original compose file from here https://gitlab.ow2.org/stamp/atos-uc-city2go/blob/master/Descriptors/Docker/docker-compose.yml, but you use a 'build' instruction, which we do not support yet...

There are two options to build these images.

Option1:
You can do it manually
```
cd root@osboxes:/home/osboxes/Proyectos/STAMP/WP2_ATOS_USE_CASE/CAMP/camp-samples/atos/build/showcase--python-2.7 && docker build -t showcase:none-python-2.7 .
```
the similar command is for the database

Option2:
build.sh should be in '/home/osboxes/Proyectos/STAMP/WP2_ATOS_USE_CASE/CAMP/camp-samples/atos/build/'. If you look it up, you will notice that it just runs two docker build commands for db and webapp

**Comment by fermenreq** [comment]
hi @vassik 

I did **Option 1**  and the docker building process it works: 
```
root@osboxes:/home/osboxes/Proyectos/STAMP/WP2_ATOS_USE_CASE/CAMP/camp-samples/atos/build/showcase--python-2.7/ShowcaseServer# docker build -t showcase:none-python-2.7 .
...
...
...
...
Removing intermediate container dbab9654093d
Successfully built 9ef0b3a661ae
```


```
root@osboxes:/home/osboxes/Proyectos/STAMP/WP2_ATOS_USE_CASE/CAMP/camp-samples/atos/compose1# docker images
REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
showcase             none-python-2.7     9ef0b3a661ae        5 minutes ago       993 MB
```
Then I go to : ``` cd compose1/ ``` and ```docker-compose up -d ``` but I get the following error cause this image doesn't exit: 
```
Pulling db (postgres:none-ubuntu-latest)...
ERROR: manifest for postgres:none-ubuntu-latest not found
```

Thanks,
Fernando - fernando.mendez@atos.net

**Comment by vassik** [comment]
Hi @fermenreq 
I believe you also need to build an image for db which is located in the build folder, i.e. 'atos/build/' which is generated by camp. There should be two folders in the build folder, i.e. there should be one for the showcase app, with the name 'showcase--python-2.7', and another one for db with the name 'postgres--ubuntu-latest'. It looks like, you have built an image for the showcase app, now you need to do the same for db.

Please go to atos/build/postgres--ubuntu-latest and run 'docker build' to build postgres:none-ubuntu-latest

**Comment by fermenreq** [comment]
hi @vassik 

There is no postgres--ubuntu-latest image for db into the build folder: 
```
root@osboxes:/home/osboxes/Proyectos/STAMP/WP2_ATOS_USE_CASE/CAMP/camp-samples/atos/build# ls
showcase--python-2.7
```
Maybe we must replace **adds: [ubuntu]** instead **adds: [postgres]** cause DB image is made from Ubuntu
[Dockerfile DB](https://gitlab.ow2.org/stamp/atos-uc-city2go/blob/master/Descriptors/Docker/db/Dockerfile)

## Images.yml
```
downloadimages:
  Ubuntu:
    features: [ubuntu]
    name: ubuntu
    tag: latest
  Python:
    features: [python]
    name: python
    tag: 2.7
buildingrules:
  Showcase:
    requires: [python]
    adds: [showcase]
    svar: [ThreadLimit, ThreadPerChild]
    depends: [postgres]
  Postgres:
    requires: [ubuntu]
    adds: [ubuntu]
maxfreebuild: 3
```

**Comment by vassik** [comment]
@fermenreq this is weird. Your images.yml is kind of different from what is in the repository. Postgres image is based on ubuntu, and adds a postgres feature. This should be right. Anyway, let's try the following:

1. git clone https://github.com/STAMP-project/camp.git
2. cd camp/samples/stamp/atos/
3. docker run -it -v $(pwd):/root/workingdir songhui/camp /bin/bash allinone.sh

This should create the build, compose1 and compose2 folders in camp/samples/stamp/atos/. The build folder should contain two subfolders, postgres-ubuntu-latest and showcase-python-2.7 which should contain docker files to build images.

**Comment by vassik** [comment]
@fermenreq I moved everything to the main camp repo, so I suggest you switch to https://github.com/STAMP-project/camp, but it should still work on the master branch of the camp-samples repo.

 It seems you are missing compose2 and a folder for the postgres image...this is weird...

Do you want to have a quick chat on skype?

**Comment by vassik** [comment]
@fermenreq 

Update: Oh sorry, you have the compose2 folder, but still missing a folder for the postgres image.

As a work around, you can build the image 'postgres:none-ubuntu-latest' from the docker file in repo/Postgres for now. We almost do not change anything in the initial docker file for DB yet, thus, it should work.

**Comment by vassik** [comment]
@fermenreq answering your question.

No this is not a mistake, this docker compose file is actually a template which i used to generate other compose files in compose1 and compose2 folders. The line you are referring to is got replaced by the generated images (in the build folder) which should be build before executing docker-compose up.

**Comment by fermenreq** [comment]
Dear @vassik 

## Solution using Update 1:

I get the following error once I built the postgres image dockerfile: 
```
root@osboxes:/home/osboxes/Proyectos/STAMP/WP2_ATOS_USE_CASE/CAMP/camp-samples/atos/repo/Postgres# docker build -t postgres:none-ubuntu-latest .

Step 3/17 : RUN apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8
 ---> Running in e3e9d91f16b0
E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
The command '/bin/sh -c apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8' returned a non-zero code: 255
```
Fixed here: https://gitlab.ow2.org/stamp/atos-uc-city2go. Please update your content 

Once done,  both images are created:

```
root@osboxes:/home/osboxes/Proyectos/STAMP/WP2_ATOS_USE_CASE/CAMP/camp-samples/atos/repo/Postgres# docker images
REPOSITORY           TAG                  IMAGE ID            CREATED              SIZE
postgres             none-ubuntu-latest   d523d03bd383        About a minute ago   604 MB
showcase             none-python-2.7      9ef0b3a661ae        2 days ago           993 MB
```

I get the following error: 
```
root@osboxes:/home/osboxes/Proyectos/STAMP/WP2_ATOS_USE_CASE/CAMP/camp-samples/atos/compose1# docker-compose up -d
my_postgres is up-to-date
cygnus-ngsi is up-to-date
cygnus-common is up-to-date
compose1_mongo_1 is up-to-date
compose1_orion_1 is up-to-date
Starting my_web ... error

ERROR: for my_web  Cannot start service web: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"chdir to cwd (\\\"/webapp/ShowcaseServer\\\") set in config.json failed: no such file or directory\"\n"

ERROR: for web  Cannot start service web: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"chdir to cwd (\\\"/webapp/ShowcaseServer\\\") set in config.json failed: no such file or directory\"\n"
ERROR: Encountered errors while bringing up the project.
```

This is part of the content of ```docker-compose.yml``` file saved in ```compose1/``` directory

```
 web:
    command: python /webapp/ShowcaseServer/manage.py runserver 0.0.0.0:80
    container_name: my_web
    depends_on:
    - db
    - orion
    environment:
    - PYTHONUSERBASE=.webapp/ShowcaseServer/
    - StartServers=2
    - MinSpareThreads=25
    - MaxSpareThreads=75
    - ThreadLimit=128
    - ThreadsPerChild=100
    - MaxRequestWorkers=150
    - MaxConnectionsPerChild=0
    - MinSpareServers=5
    - MaxSpareServers=10
    image: showcase:none-python-2.7
    ports:
    - 80:80
    volumes:
    - ./webapp:/webapp
version: '2'
volumes:
  db_data:
    external: true
```

Best,
Fernando - fernando.mendez@atos.net
