### ISSUE TITLE
CAMP generate fails to find configurations when stacks involve transitive closure

### ISSUE THREAD

**Issue by fchauvel** [STAMP-project/camp#74]
#### Characteristics

-   **Issue Type**: bug
-   **Reproducibility**: always
-   **Severity**: major
-   **Tool/Service/Component**: CAMP 
-   **Execution Environment**:
    -  CAMP v0.6.0 (MIT)
    - Linux 4.9.0-8-amd64 (debian 9.8)
    - Python 3.5.3.final.0
    - Z3 4.7.1
    - Docker version 18.09.4, build d14af54
    - docker-compose version 1.23.0, build c8524dc1
-   **Reporter**: Franck Chauvel

#### Description

CAMP fails to find configuration when the configuration involve ordering component stacks "side-by-side". as in the example below:

```yaml
goals:
  running: [ MyService ]

components:

  django:
    provides_services: [ MyService ]
    requires_features: [ Python, HttpProxy ]


  apache:
    provides_features: [ HttpProxy ]
    requires_features: [ Linux ]


  python:
    provides_features: [ Python ]
    requires_features: [ Linux ]


  ubuntu:
    provides_features: [ Linux ]
```

#### Steps to reproduce
Just run "CAMP generate -d . --all" and it does not found any configuration. It does not complain either and one could expect it to at least warn the user about it.
