### ISSUE TITLE
CAMP generate put multiple implementations of the same feature in single stacks

### ISSUE THREAD

**Issue by fchauvel** [STAMP-project/camp#75]
#### Characteristics

-   **Issue Type**: bug
-   **Reproducibility**: always
-   **Severity**: Major
-   **Tool/Service/Component**: CAMP generate (v0.6.1)
    - Linux 4.9.0-8-amd64 (debian 9.8)
    - Python 3.5.3.final.0
    - Z3 4.7.1
    - Docker version 18.09.4, build d14af54
    - docker-compose version 1.23.0, build c8524dc1
-   **Execution Environment**: \[platform, OS, etc]
-   **Reporter**: @fchauvel 

#### Description
Given the following `camp.yml`, I expect that CAMP does not generate stacks that includes mutliple implementation of the same "feature". In this example, it the the HTTP proxy features. While both the NGinx & Apache component offer that feature, it does not make sense to get both in the same software stacks.

```yaml
components:

  django:
    provides_services: [ MyService ]
    requires_features: [ Python, HttpProxy ]

  apache:
    provides_features: [ HttpProxy ]
    requires_features: [ Linux ]

  nginx:
    provides_features: [ HttpProxy ]
    requires_features: [ Linux ]

  python:
    provides_features: [ Python ]
    requires_features: [ Linux ]

  ubuntu:
    provides_features: [ Linux ]
```
The configurations that CAMP generates are the following:
![configurations](https://user-images.githubusercontent.com/981112/65580332-bb6c8900-df79-11e9-981c-2c759d5c7e3c.png)

#### Steps to reproduce

```console
$ camp generate -d . --all
```

#### [Help on issue template](https://github.com/STAMP-project/eclipse-ide/blob/master/.github/ISSUE_DOC.md)
Preview to follow the link or open file .github/ISSUE_DOC.md
