### ISSUE TITLE
CAMP realize fails to select template files

### ISSUE THREAD

**Issue by fchauvel** [STAMP-project/camp#98]
#### Characteristics

-   **Issue Type**: bug
-   **Reproducibility**: always
-   **Severity**: crash
-   **Tool/Service/Component**: CAMP v0.7.1 
-   **Execution Environment**: 
     - Linux 4.9.0-8-amd64 (debian 9.8)
     - Python 3.5.3.final.0
     - Z3 4.8.6
     - Docker version 18.09.4, build d14af54
     - docker-compose version 1.23.0, build c8524dc1
-   **Reporter**: @fchauvel on behalf of @assadOW2 

#### Description
CAMP fails when the variability model includes a component level realization, where the file to select refers to file located into specific component templates. For instance:

```yaml
jetty:
   realization:
      - select: lutece/jetty_entrypoint.sh
        instead_of:
           - lutece/tomcat_entrypoint.sh
        as: lutece/entrypoint.sh
```

#### Steps to reproduce

1. Create a variability model as explained above
2. Run the following commands:

```console
user@machine$ camp generate -d. --all
user@machine$ camp realize -d .
CAMP v0.7.1 (MIT)
Copyright (C) 2017 -- 2019 SINTEF Digital

Loaded './camp.yml'.
Loading configurations from './out' ...
Unexpected error:
 - [Errno 2] No such file or directory: './out/config_1/lutece/jetty_entrypoint.sh'
   In file: /home/fchauvel/Documents/camp/.py35/lib/python3.5/shutil.py
      120: with open(src, 'rb') as fsrc:
   Please report this at 'https://github.com/STAMP-project/camp/issues'.

That's all folks!

```
